language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install: 
  - composer update --prefer-source

script: 
  - phpunit --bootstrap vendor/autoload.php tests/
